---
title: "Budget_Analysis"
author: "Greg Sanders"
date: "2022-10-09"
output: html_document
---
# Setup
```{r setup, include=FALSE}

library(tidyverse)
library(Cairo)
library(ggthemes)
library(car)
library(extrafont)
library(csis360)
library(scales)
# --------------------------------------------------------------------------------
# add theme

source("theme/chart_theme.R")
source("theme/money_labels.R")


knitr::opts_chunk$set(echo = TRUE)
load("engine_budget.rda")
```

## Top Projects
```{r PreprocessPSC}



topProject<-engine_budget %>% group_by (ProjectName) %>% #ProjectNumber
  summarise(Amount_OMB23_GDP21=sum(Amount_OMB23_GDP21,na.rm=TRUE),
            Amount_2021=sum(ifelse(FY==2021,Amount_OMB23_GDP21,0),na.rm=TRUE))%>%
              # group_by (Organization) %>%
    mutate(rank_total=rank(desc(Amount_OMB23_GDP21)),
                        rank_2021=rank(desc(Amount_2021)))
topProject %>% arrange(desc(Amount_OMB23_GDP21))

# topProject$topProjectID<-
#   ifelse(topProject$rank_2021<=7 | topProject$rank_total<=12,topProject$ProjectNumber,NA)
topProject$topProjectText<-
  ifelse(topProject$rank_2021<=9 | topProject$rank_total<=9,topProject$ProjectName,NA)

engine_budget<-engine_budget[,!colnames(engine_budget) %in% c("topProjectText","rank_total","rank_2021")]

engine_budget<-left_join(engine_budget,topProject %>% select(-Amount_OMB23_GDP21,-Amount_2021),
          by=c("ProjectName"))

engine_budget$topProjectText[is.na(engine_budget$topProjectText) & !is.na(engine_budget$ProjectName)]<-
  paste("Other",engine_budget$Organization[is.na(engine_budget$topProjectText) & !is.na(engine_budget$ProjectName)],"projects")

engine_budget$topProjectText<-factor_wrap(factor(engine_budget$topProjectText))

summary(engine_budget$topProjectText)


```


## Actual setup
```{r actual}
# ================================================================================
# charting engines - actual  
# --------------------------------------------------------------------------------
# clean data 
#   (note: this filtering section creates a dataset for only actual values in the 
#   ...budget line, in addition to enacted and projected for the most recent FYDP



engine_just_actual <- engine_budget %>%
  filter(
    PByear == "2000 FYDP" & FY == "1998" |
      PByear == "2001 FYDP" & FY == "1999" |
      PByear == "2002 FYDP" & FY == "2000" |
      PByear == "2003 FYDP" & FY == "2001" |
      PByear == "2004 FYDP" & FY == "2002" |
      PByear == "2005 FYDP" & FY == "2003" |
      PByear == "2006 FYDP" & FY == "2004" |
      PByear == "2007 FYDP" & FY == "2005" |
      PByear == "2008 FYDP" & FY == "2006" |
      PByear == "2009 FYDP" & FY == "2007" |
      PByear == "2010 FYDP" & FY == "2008" |
      PByear == "2011 FYDP" & FY == "2009" |
      PByear == "2012 FYDP" & FY == "2010" |
      PByear == "2013 FYDP" & FY == "2011" |
      PByear == "2014 FYDP" & FY == "2012" |
      PByear == "2015 FYDP" & FY == "2013" |
      PByear == "2016 FYDP" & FY == "2014" |
      PByear == "2017 FYDP" & FY == "2015" |
      PByear == "2018 FYDP" & FY == "2016" |
      PByear == "2019 FYDP" & FY == "2017" |
      PByear == "2020 FYDP" & FY == "2018" |
      PByear == "2021 FYDP" & FY == "2019" |
      PByear == "2022 FYDP" & FY == "2020" |
      PByear == "2023 FYDP" 
  ) %>% mutate(PByear="Actual")

engine_just_actual$Projection<-"Actual"
engine_budget$Projection<-"Projection"
summary(factor(engine_just_actual$stage))
engine_actual<-engine_just_actual %>%
  mutate(
    stagename=factor_wrap(stage,nwrap=14),
    stage = recode(
      stage,
      "'(6.1) Basic Research' = '6.1';
      '(6.2) Applied Research' = '6.2';
      '(6.3) Advanced Technology Development' = '6.3';
      '(6.4) Advanced Component Development & Prototypes' = '6.4';
      '(6.5) System Development & Demonstration' = '6.5';
      '(6.7) Operational Systems Development' = '6.7'"
    )
  ) %>% 
  filter(Amount_Then_Year != 0) %>%
  group_by(FY, Organization, stage, stagename,topProjectText) %>%
  dplyr::summarize(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
                   Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE))

summary(factor(engine_actual$stage))
engine_actual_wide <-
  spread(engine_actual, key = "FY", value = "Amount_Then_Year")

engine_actual$FY <- as.numeric(engine_actual$FY)

empty<-expand.grid(
  stage = c("6.1",
            "6.2",
            "6.3",
            "6.4",
            "6.5",
            "6.7",
            "Total"),
  Organization = c("Army",
                   "Navy",
                   "Air Force",
                   "Total"),
  FY=seq(from=2017,to=2023))

empty$Amount_Then_Year<-0
empty$Amount_OMB23_GDP21<-0




```



#Future

## FYDP year

```{r esfydp}
# ================================================================================
# charting engines - future  
# --------------------------------------------------------------------------------
# engine spending (by FYDP year)

engine_budget_future <- rbind(engine_budget,engine_just_actual %>% filter(FY<=2021)) %>%
  mutate(FY = as.numeric(FY)) %>%
  group_by(PByear, FY, Projection) %>%
  filter(Amount_Then_Year != 0) %>%
  dplyr::summarize(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
                   Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE))

#Quick examination of variance in number of years tracked by each budget
# View(engine_budget_future)
engine_budget_future %>% group_by(PByear) %>%
  dplyr::summarise(fy_count=length(FY),
                   min_fy=min(FY),
                   max_fy=max(FY),
                   )


(
  plot_ebf <- ggplot(engine_budget_future) +
    geom_line(aes(
      x = FY,
      y = Amount_OMB23_GDP21,
      group = PByear,
      alpha = PByear,
      linetype=Projection
    ), color = "#554449", size = 1) +
    ggtitle("DoD RDT&E Aircraft Engine Spending Projections") + 
    geom_point(aes(      x = FY,
      y = Amount_OMB23_GDP21,
      shape=Projection))+
    chart_theme + 
    scale_y_continuous(label = unit_format(unit = "M", scale = 1e-6)) +

    xlab("Fiscal Year") + 
    ylab("Constant 2021 $") +
    scale_shape_manual(values=c(16,20))
)

ggsave(
  "charts/Amount_total.svg",
  plot_ebf,
  device = "svg",
  width = 8,
  height = 6,
  units = "in"
)
write.csv(
  engine_budget_future %>% 
    pivot_longer(names_to="Metric",cols=c(Amount_Then_Year,Amount_OMB23_GDP21)) %>%
    pivot_wider(
    names_from=FY,values_from=value) %>%
    arrange(Metric,PByear),
    file="charts/Amount_total.csv",
  na = "",
  row.names = FALSE
  )
  

```


## Service
```{r esservice}
# --------------------------------------------------------------------------------
# engine spending by Service

engine_budget_organization_future <- engine_budget %>%
  mutate(FY = as.numeric(FY)) %>%
  group_by(PByear, FY, Organization) %>%
  filter(Amount_Then_Year != 0) %>%
  dplyr::summarize(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
                   Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE))

engine_budget_organization_future_wide <-
  spread(engine_budget_organization_future, key = "FY", value = "Amount_Then_Year")

(
  plot_ebf <- ggplot(engine_budget_organization_future) +
    geom_line(
      aes(
        x = FY,
        y = Amount_OMB23_GDP21,
        group = PByear,
        alpha = PByear
      ),
      color = "#554449",
      size = 1
    ) +
    facet_wrap(~ Organization) +
    scale_y_continuous(label = unit_format(unit = "M", scale = 1e-6)) +
    scale_x_continuous(
      breaks = seq(2000, 2025, by = 5),
      labels = function(x) {
        paste("'",substring(as.character(x), 3, 4),sep="")
      }
    ) +
    ggtitle("DoD RDT&E Aircraft Engine Spending Projections by Service") +
    chart_theme +
    xlab("Fiscal Year") + 
    ylab("Constant 2021 $") 
)

ggsave(
  "charts/Amount_service.svg",
  plot_ebf,
  device = "svg",
  width = 12,
  height = 6,
  units = "in"
)
```


## Project Name
```{r EngineProjectName}
# --------------------------------------------------------------------------------
# engine spending by project name

engine_budget_project_future <- engine_budget %>%
  mutate(FY = as.numeric(FY)) %>%
  group_by(PByear, FY, topProjectText) %>%
  filter(Amount_Then_Year != 0) %>%
  dplyr::summarize(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
                   Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE))

engine_budget_project_future_wide <-
  spread(engine_budget_project_future, key = "FY", value = "Amount_Then_Year")

(
  plot_ebf <- ggplot(engine_budget_project_future) +
    geom_line(
      aes(
        x = FY,
        y = Amount_OMB23_GDP21,
        group = PByear,
        alpha = PByear
      ),
      color = "#554449",
      size = 1
    ) +
    facet_wrap(~ topProjectText) +
    scale_y_continuous(label = unit_format(unit = "M", scale = 1e-6)) +
    scale_x_continuous(
      breaks = seq(2000, 2025, by = 5),
      labels = function(x) {
        paste("'",substring(as.character(x), 3, 4),sep="")
      }
    ) +
    ggtitle("DoD RDT&E Aircraft Engine Spending Projections by project") +
    chart_theme +
    xlab("Fiscal Year") + 
    ylab("Constant 2021 $") 
)
```


## Stage
```{r Stage}
# --------------------------------------------------------------------------------
# engine spending by Stage

engine_budget_stage_future <- engine_budget %>%
  mutate(FY = as.numeric(FY)) %>%
  filter(stage != "NA") %>%
  group_by(PByear, FY, stage) %>%
  filter(Amount_Then_Year != 0) %>%
  dplyr::summarize(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
                   Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE))

engine_budget_stage_future_wide <-
  spread(engine_budget_stage_future, key = "FY", value = "Amount_Then_Year")

(
  plot_ebf <- ggplot(engine_budget_stage_future) +
    geom_line(
      aes(
        x = FY,
        y = Amount_OMB23_GDP21,
        group = PByear,
        alpha = PByear
      ),
      color = "#554449",
      size = 1
    ) +
    facet_wrap(~ stage) +
    scale_y_continuous(label = unit_format(unit = "M", scale = 1e-6)) +
    scale_x_continuous(
      breaks = seq(2000, 2025, by = 5),
      labels = function(x) {
        paste("'",substring(as.character(x), 3, 4),sep="")
      }
    ) +
    ggtitle("DoD RDT&E Aircraft Engine Spending Projections by Stage") +
    chart_theme +
    xlab("Fiscal Year") + 
    ylab("Constant 2021 $")  
)

ggsave(
  "charts/Amount_stage.svg",
  plot_ebf,
  device = "svg",
  width = 10,
  height = 8,
  units = "in"
)
```

## Service and Stage
```{r ServiceStage}
# --------------------------------------------------------------------------------
# engine spending by Service and stage

engine_budget_stage_service_future <- engine_budget %>%
  mutate(FY = as.numeric(FY)) %>%
  mutate(
    stage = recode(
      stage,
      "'(6.1) Basic Research' = '6.1';
      '(6.2) Applied Research' = '6.2';
      '(6.3) Advanced Technology Development' = '6.3';
      '(6.4) Advanced Component Development & Prototypes' = '6.4';
      '(6.5) System Development & Demonstration' = '6.5';
      '(6.7) Operational Systems Development' = '6.7'"
    )
  ) %>% 
  mutate(Organization = factor(Organization,
                               levels = c("Army",
                                          "Navy",
                                          "Air Force"))) %>%
  filter(stage != "NA") %>%
  group_by(PByear, FY, Organization, stage) %>%
  filter(Amount_Then_Year != 0) %>%
  dplyr::summarize(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
                   Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE))

engine_budget_stage_service_future_wide <-
  spread(engine_budget_stage_service_future, key = "FY", value = "Amount_Then_Year")

(
  plot_ebf <- ggplot(engine_budget_stage_service_future) +
    geom_line(
      aes(
        x = FY,
        y = Amount_OMB23_GDP21,
        group = PByear,
        alpha = PByear
      ),
      color = "#554449",
      size = 1
    ) +
    facet_grid(Organization ~ stage) +
    scale_y_continuous(label = unit_format(unit = "M", scale = 1e-6)) +
    scale_x_continuous(
      breaks = seq(2000, 2025, by = 5),
      labels = function(x) {
        paste("'",substring(as.character(x), 3, 4),sep="")
      }
    ) +
    ggtitle("DoD RDT&E Aircraft Engine Spending Projections by Stage and Service") +
    chart_theme +
    theme(strip.text.x = element_text(size = 10)) +
    theme(strip.text.y = element_text(size = 10)) +
    xlab("Fiscal Year") +
    ylab("Constant 2021 $") 
)

# ggsave(
#   "charts/Amount_service_stage.svg",
#   plot_ebf,
#   device = "svg",
#   width = 14,
#   height = 8,
#   units = "in"
# )
```

# Actual


## Annual

```{r esa}
# ================================================================================
# charting engines - actual  
# --------------------------------------------------------------------------------
# engine spending (by FYDP year)
engine_actual_FY <- engine_actual %>%
  # filter(Amount_Then_Year != 0) %>%
  group_by(FY) %>%
  dplyr::summarize(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
                   Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE))%>%
  left_join(rdte %>%select(Fiscal_Year,TOA),by=c("FY"="Fiscal_Year"))

engine_actual


(
  plot_eba <- build_plot(engine_actual,
                         chart_geom="Line Chart",
                         share=FALSE,
                         x_var="FY",
                         y_var="Amount_OMB23_GDP21",
                         format=TRUE
                         ) +
    ggtitle("DoD RDT&E Aircraft Engine Spending Projections") +
    scale_y_continuous(label = unit_format(unit = "M", scale = 1e-6)) +
    xlab("Fiscal Year") + 
    ylab("Constant 2021 $") +geom_vline(
      xintercept = 2021,
      color = "#554449",
      alpha = .5,
      linetype = "solid"
    ) +
    geom_vline(
      xintercept = 2023,
      color = "#554449",
      linetype = "dotted"
    )+ 
    scale_x_continuous(
      breaks = seq(2000, 2027, by = 10),
      labels = function(x) {
      paste("'",substring(as.character(x), 3, 4),sep="")
      }
    ) +
    geom_rect(
      # aes(
        xmin = 2021,
        xmax = Inf,
        ymin = 0,
        ymax = Inf,
        alpha = 0.01,
        fill = "grey",
      # ),
      
      data = empty#engine_actual#engine_actual_project
    ) 
)

# ggsave(
#   "charts/Amount_total.svg",
#   plot_ebf,
#   device = "svg",
#   width = 8,
#   height = 6,
#   units = "in"
# )
```

## Services
```{r esa}
# ================================================================================
# charting engines - actual  
# --------------------------------------------------------------------------------
# engine spending (by FYDP year)

(
  plot_eorgact <- build_plot(engine_actual,
                         chart_geom="Line Chart",
                         share=FALSE,
                         x_var="FY",
                         y_var="Amount_OMB23_GDP21",
                         facet="Organization",
                         format=TRUE,
                         caption="Budget Documents for Army, Navy, and Air Force; CSIS Analysis."
                         ) +
    ggtitle("DoD RDT&E Aircraft Engine Spending Projections") +
    scale_y_continuous(label = unit_format(unit = "M", scale = 1e-6)) +
    xlab("Fiscal Year") + 
    ylab("Constant 2021 $") +geom_vline(
      xintercept = 2021,
      color = "#554449",
      alpha = .5,
      linetype = "solid"
    ) +
    geom_vline(
      xintercept = 2023,
      color = "#554449",
      linetype = "dotted"
    )+ 
    geom_rect(
      # aes(
        xmin = 2021,
        xmax = Inf,
        ymin = 0,
        ymax = Inf,
        alpha = 0.01,
        fill = "grey",
      # ),
      
      # data = empty#engine_actual#engine_actual_project
    ) 
)

ggsave(
  "charts/actual_amount_service.svg",
  plot_eorgact+labs(title=NULL),
  # device = "svg",
  width = 6.5,
  height = 3.5,
  units = "in"
)

write.csv(
  engine_actual %>% 
        group_by(FY,Organization) %>%
    summarise(
    Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
    Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE)
    ) %>%
    pivot_longer(names_to="Metric",cols=c(Amount_Then_Year,Amount_OMB23_GDP21)) %>%
    pivot_wider(
    names_from=FY,values_from=value) %>%
    arrange(Metric,Organization),
    file="charts/actual_amount_service.csv",
  na = "",
  row.names = FALSE
  )
  

colnames(engine_budget)


```

## Project Facet
```{r facet1}

# facet --------------------------------------------------------------------------


engine_actual_1 <- engine_actual %>%
  filter(Amount_Then_Year != 0) %>%
  group_by(FY, topProjectText,Organization) %>%
  dplyr::summarize(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
                   Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE))


# project_order<-distinct(engine_budget %>% select(topProjectText,rank_total) %>% arrange(rank_total)) %>%
#   filter(!topProjectText %in% c("Other Army projects","Other Navy projects","Other Air Force\nprojects"))
# write.csv(project_order,file="project_order.csv")

engine_actual_1$topProjectText<-factor(engine_actual_1$topProjectText,
levels=c("F135",
"F136",
"Aircraft Engine\nComponent\nImprovement Program\n(USAF)",
	"Adaptive Engine\nTransition\nProgram/Next Gen\nAdaptive Propulsion",
	"Aircraft Engine\nComponent\nImprovement Program\n(USN)",
	"Materials for\nStructures,\nPropulsion, and\nSubsystems",
	"Turbine Engine\nTechnology",
	"Improved Turbine\nEngine Program",
	"Aircraft Propulsion\nSubsystems Int",
	"Advanced Turbine\nEngine Gas\nGenerator",
	"Advanced Propulsion\nTechnology",
	"AV-8B",
	"Combustion and\nMechanical Systems",
	"Other Army projects",
	"Other Navy projects",
	"Other Air Force\nprojects")
)
# distinct(engine_actual_1 %>%group_by()%>% select(topProjectText,topProjectText2))
(
  facet <-
    ggplot() + geom_area(aes(y = Amount_OMB23_GDP21, x = FY, fill= Organization),
                         data = engine_actual_1,
                         
                         stat = "identity") +
    geom_rect(
      aes(
        xmin = 2021,
        xmax = Inf,
        ymin = 0,
        ymax = Inf
      ),
      alpha = .02,
      fill = "grey",
      data = engine_actual_1
    ) +
    facet_wrap(~ topProjectText) +
    chart_theme +
    theme(strip.text.x = element_text(size = 8)) +
    theme(strip.text.y = element_text(size = 8)) +
    scale_y_continuous(label = unit_format(unit = "M", scale = 1e-6)) +
    scale_x_continuous(
      breaks = seq(2000, 2027, by = 5),
      labels = function(x) {
        paste("'",substring(as.character(x), 3, 4),sep="")
      }
    ) +
    scale_fill_manual(values=c("#72a0c1","#32602F","#1d2d5c"))+
    ggtitle("DoD RDT&E Aircraft Engine Spending By Project") +
    xlab("Fiscal Year") +
    ylab("Constant 2021 $") + 
    geom_vline(
      xintercept = 2021,
      color = "#554449",
      alpha = .5,
      linetype = "solid"
    ) +
    geom_vline(
      xintercept = 2023,
      color = "#554449",
      linetype = "dotted"
    )
)

ggsave(
  "charts/actual_Amount_project.svg",
  facet+theme(legend.position="bottom")+labs(title=NULL),
  device = "svg",
  width = 6.5,
  height = 6,
  units = "in"
)

write.csv(
  engine_actual_1 %>% 
    pivot_longer(names_to="Metric",cols=c(Amount_Then_Year,Amount_OMB23_GDP21)) %>%
    pivot_wider(
    names_from=FY,values_from=value) %>%
    arrange(Metric,topProjectText),
    file="charts/actual_Amount_project.csv",
  na = "",
  row.names = FALSE
  )
# colnames(engine_actual) ProgramElement

colnames(engine_budget)



```


## Stage Facet
```{r Facet2}
# facet 2 ------------------------------------------------------------------------
summary(factor(engine_actual$stagename))
summary(factor_wrap(engine_budget$stage,nwrap=2))

  (
    plot_eorgstageact <- build_plot(engine_actual,
                           chart_geom="Line Chart",
                           share=FALSE,
                           x_var="FY",
                           y_var="Amount_OMB23_GDP21",
                           facet_var="Organization",
                           second_var='stagename',
                           format=TRUE,
                           caption="Budget Documents for Army, Navy, and Air Force; CSIS Analysis."
                           ) +
      ggtitle("DoD RDT&E Aircraft Engine Spending Projections") +
      scale_y_continuous(label = unit_format(unit = "M", scale = 1e-6)) +
         scale_x_continuous(
        breaks = seq(2000, 2027, by = 10),
        labels = function(x) {
        paste("'",substring(as.character(x), 3, 4),sep="")
        }
      ) +
      xlab("Fiscal Year") + 
      ylab("Constant 2021 $") +geom_vline(
        xintercept = 2021,
        color = "#554449",
        alpha = .5,
        linetype = "solid"
      ) +
      geom_vline(
        xintercept = 2023,
        color = "#554449",
        linetype = "dotted"
      )+ 
      geom_rect(
        # aes(
          xmin = 2021,
          xmax = Inf,
          ymin = 0,
          ymax = Inf,
          alpha = 0.01,
          fill = "grey",
        # ),
        
        # data = empty#engine_actual#engine_actual_project
      ) 
  )
  
  ggsave(
    "charts/actual_amount_service_stage_nocrosstab.svg",
    plot_eorgstageact+theme(legend.position="non")+labs(title=NULL),
    device = "svg",
    width = 8,
    height = 4,
    units = "in"
  )

write.csv(
  engine_actual %>% 
    group_by(FY, stage,Organization) %>%
  dplyr::summarize(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
                   Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE)) %>%
    pivot_longer(names_to="Metric",cols=c(Amount_Then_Year,Amount_OMB23_GDP21)) %>%
    pivot_wider(
    names_from=FY,values_from=value) %>%
    arrange(Metric,Organization,stage),
    file="charts/actual_amount_service_stage.csv",
  na = "",
  row.names = FALSE
  )
# colnames(engine_actual) ProgramElement


total <- engine_actual %>%
  group_by(FY) %>%
  dplyr::summarize(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
                   Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE)) %>% 
  mutate(Organization = "Total") %>% 
  as.data.frame(.)

total_organization <- engine_actual %>%
  group_by(FY, Organization) %>%
  dplyr::summarize(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
                   Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE)) %>% 
  as.data.frame(.)

total <- total %>%
  rbind(total_organization) %>%
  mutate(stage = "Total")

rd6.1 <-  engine_actual %>%
  filter(stage == "6.1") %>% 
  group_by(FY) %>%
  dplyr::summarize(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
                   Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE)) %>% 
  mutate(Organization = "Total") %>% 
  as.data.frame(.)

rd6.1_organization <-  engine_actual %>%
  filter(stage == "6.1") %>% 
  group_by(FY, Organization) %>%
  dplyr::summarize(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
                   Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE)) %>% 
  as.data.frame(.)

rd6.1 <- rd6.1 %>%
  rbind(rd6.1_organization) %>%
  mutate(stage = "6.1")

rd6.2 <-  engine_actual %>%
  filter(stage == "6.2") %>% 
  group_by(FY) %>%
  dplyr::summarize(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
                   Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE)) %>% 
  mutate(Organization = "Total") %>% 
  as.data.frame(.)  

rd6.2_organization <-  engine_actual %>%
  filter(stage == "6.2") %>% 
  group_by(FY, Organization) %>%
  dplyr::summarize(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
                   Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE)) %>% 
  as.data.frame(.)

rd6.2 <- rd6.2 %>%
  rbind(rd6.2_organization) %>%
  mutate(stage = "6.2")

rd6.3 <-  engine_actual %>%
  filter(stage == "6.3") %>% 
  group_by(FY) %>%
  dplyr::summarize(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
                   Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE)) %>% 
  mutate(Organization = "Total") %>% 
  as.data.frame(.)  

rd6.3_organization <-  engine_actual %>%
  filter(stage == "6.3") %>% 
  group_by(FY, Organization) %>%
  dplyr::summarize(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
                   Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE)) %>% 
  as.data.frame(.)

rd6.3 <- rd6.3 %>%
  rbind(rd6.3_organization) %>%
  mutate(stage = "6.3")

rd6.4 <-  engine_actual %>%
  filter(stage == "6.4") %>% 
  group_by(FY) %>%
  dplyr::summarize(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
                   Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE)) %>% 
  mutate(Organization = "Total") %>% 
  as.data.frame(.)  

rd6.4_organization <-  engine_actual %>%
  filter(stage == "6.4") %>% 
  group_by(FY, Organization) %>%
  dplyr::summarize(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
                   Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE)) %>% 
  as.data.frame(.)

rd6.4 <- rd6.4 %>%
  rbind(rd6.4_organization) %>%
  mutate(stage = "6.4")

rd6.5 <-  engine_actual %>%
  filter(stage == "6.5") %>% 
  group_by(FY) %>%
  dplyr::summarize(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
                   Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE)) %>% 
  mutate(Organization = "Total") %>% 
  as.data.frame(.)  

rd6.5_organization <-  engine_actual %>%
  filter(stage == "6.5") %>% 
  group_by(FY, Organization) %>%
  dplyr::summarize(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
                   Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE)) %>% 
  as.data.frame(.)

rd6.5 <- rd6.5 %>%
  rbind(rd6.5_organization) %>%
  mutate(stage = "6.5")

rd6.7 <-  engine_actual %>%
  filter(stage == "6.7") %>% 
  group_by(FY) %>%
  dplyr::summarize(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
                   Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE)) %>% 
  mutate(Organization = "Total") %>% 
  as.data.frame(.)  

rd6.7_organization <-  engine_actual %>%
  filter(stage == "6.7") %>% 
  group_by(FY, Organization) %>%
  dplyr::summarize(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
                   Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE)) %>% 
  as.data.frame(.)

rd6.7 <- rd6.7 %>%
  rbind(rd6.7_organization) %>%
  mutate(stage = "6.7")

engine_actual_organization <- engine_actual %>%
  group_by(FY, Organization) %>%
  dplyr::summarize(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE),
                   Amount_OMB23_GDP21 = sum(Amount_OMB23_GDP21, na.rm = TRUE)) 
  
total <- total %>%
  rbind(rd6.1, rd6.2, rd6.3, rd6.4, rd6.5, rd6.7) %>%
  mutate(
    stage = factor(stage, levels = c("6.1",
                                     "6.2",
                                     "6.3",
                                     "6.4",
                                     "6.5",
                                     "6.7",
                                     "Total")),
    Organization = factor(Organization, levels = c("Army",
                                                   "Navy",
                                                   "Air Force",
                                                   "Total"))
  )

summary( total$stage)




(
  super_facet <- total %>%
    
    ggplot() +
    
    geom_area(aes(y = Amount_OMB23_GDP21, x = FY),
                         # data = engine_actual_project,
                         stat = "identity") +
    facet_grid(Organization ~ stage) +
    geom_rect(
      # aes(
        xmin = 2021,
        xmax = Inf,
        ymin = 0,
        ymax = Inf,
        alpha = 0.05,
        fill = "grey",
      # ),
      
      data = empty#engine_actual#engine_actual_project
    ) +
    chart_theme +
    theme(strip.text.x = element_text(size = 8)) +
    theme(strip.text.y = element_text(size = 8)) +
    scale_y_continuous(label = unit_format(unit = "M", scale = 1e-6)) +
    scale_x_continuous(
      breaks = seq(2000, 2027, by = 4),
      labels = function(x) {
        paste("'",substring(as.character(x), 3, 4),sep="")
      }
    ) +
    ggtitle("DoD RDT&E Aircraft Engine Spending by Service and Stage") +
    xlab("Fiscal Year") +
    ylab("Constant 2021 $") + 
    geom_vline(
      xintercept = 2021,
      color = "#554449",
      alpha = .5,
      linetype = "solid"
    ) +
    geom_vline(
      xintercept = 2023,
      color = "#554449",
      linetype = "dotted"
    )
)

ggsave(
  "charts/actual_Amount_service_stage.svg",
  super_facet,
  device = "svg",
  width = 20,
  height = 8,
  units = "in"
)

```

#Old code

```{r engine_comparison}

# # ================================================================================
# # chart engine comparison 
# # --------------------------------------------------------------------------------
# # read topline data 
# 
# read_topline <- read_delim("budget/data/topline.csv",delim="\t")
# 
# topline <- read_topline %>%
#   select(FY, army, navy, air_force, dod_total, us_total) %>%
#   gather(army:us_total, key = "ProjectName", value = "Amount_Then_Year")
# #mutate(Amount_OMB23_GDP21 = Amount_Then_Year / deflator)
# 
# 
# 
# # --------------------------------------------------------------------------------
# # clean and combine data
# # --------------------------------------------------------------------------------
# 
# # engine_actual <- filter(
# #   engine_budget,
# #   PByear == "2000 FYDP" & FY == "1998" |
# #     PByear == "2001 FYDP" & FY == "1999" |
# #     PByear == "2002 FYDP" & FY == "2000" |
# #     PByear == "2003 FYDP" & FY == "2001" |
# #     PByear == "2004 FYDP" & FY == "2002" |
# #     PByear == "2005 FYDP" & FY == "2003" |
# #     PByear == "2006 FYDP" & FY == "2004" |
# #     PByear == "2007 FYDP" & FY == "2005" |
# #     PByear == "2008 FYDP" & FY == "2006" |
# #     PByear == "2009 FYDP" & FY == "2007" |
# #     PByear == "2010 FYDP" & FY == "2008" |
# #     PByear == "2011 FYDP" & FY == "2009" |
# #     PByear == "2012 FYDP" & FY == "2010" |
# #     PByear == "2013 FYDP" & FY == "2011" |
# #     PByear == "2014 FYDP" & FY == "2012" |
# #     PByear == "2015 FYDP" & FY == "2013" |
# #     PByear == "2016 FYDP" & FY == "2014" |
# #     PByear == "2017 FYDP" & FY == "2015" |
# #     PByear == "2018 FYDP" & FY == "2016" |
# #     PByear == "2018 FYDP" & FY == "2017" |
# #     PByear == "2018 FYDP" & FY == "2018"
# # )
# 
# 
# 
# engine_actual_project  <- engine_actual %>%
#   group_by(ProjectName, FY) %>%
#   summarise(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE)) %>%
#   filter(Amount_Then_Year != 0 & FY<2018) %>%
#   dplyr::left_join(deflate_year, by = "FY") %>%
#   mutate(Amount_OMB23_GDP21 = Amount_Then_Year / deflator) %>%
#   select(-deflator)
#   
# #I don't see the point of this, spreading and then gathering just counteracts itself.
# # engine_actual_wide <-
# #   spread(engine_actual_project, key = "ProjectName", value = "Amount_Then_Year")
# # 
# # engine_actual_wide[is.na(engine_actual_wide)] <- 0
# # 
# # colnames(engine_actual_wide)
# # engine_actual_wide <-
# #   gather(
# #     engine_actual_wide,
# #     "ACFT Demo Engines":"Veh Prop & Struct Tech",
# #     key = "ProjectName",
# #     value = "Amount_Then_Year"
#   # )
# 
# #I don't see the point of any of this either
# # data_fy <- select(engine_actual_wide, FY)
# # 
# # engine_actual_wide <- select(engine_actual_wide,-FY)
# # 
# # engine_actual_wide <- cbind(data_fy, engine_actual_wide)
# 
# # engine_actual_wide$FY <- as.numeric(engine_actual_wide$FY)
# 
# 
# 
# engine_actual_project <- rbind(engine_actual_project, topline)
# data_year <- engine_actual_project
# data_year <- mutate(data_year, fy2 = FY + 1)
# data_year <- select(data_year,-FY)
# colnames(data_year)[colnames(data_year) == "fy2"] <- "FY"
# 
# engine_comparison <-
#   left_join(engine_actual_project, data_year, by = c("ProjectName", "FY"))
# engine_comparison <- filter(engine_comparison, FY != 1998 |
#                               FY != 1997)
# engine_comparison <-
#   select(engine_comparison, FY, ProjectName, Amount_Then_Year.x, Amount_Then_Year.y)
# engine_comparison_topline <- filter(
#   engine_comparison,
#   ProjectName == "us_total" |
#     ProjectName == "dod_total" |
#     ProjectName == "army" |
#     ProjectName == "navy" |
#     ProjectName == "air_force"
# )
# engine_comparison <- engine_comparison %>%
#   filter(ProjectName != "us_total") %>%
#   filter(ProjectName != "dod_total") %>%
#   filter(ProjectName != "army") %>%
#   filter(ProjectName != "navy") %>%
#   filter(ProjectName != "air_force")
# 
# engine_comparison <- engine_comparison %>%
#   group_by(FY) %>%
#   summarise(
#     Amount_Then_Year.x = sum(Amount_Then_Year.x, na.rm = TRUE),
#     Amount_Then_Year.y = sum(Amount_Then_Year.y, na.rm = TRUE)
#   ) %>%
#   mutate(ProjectName = "Engines") %>%
#   select(FY, ProjectName, Amount_Then_Year.x, Amount_Then_Year.y) %>%
#   rbind(engine_comparison_topline)
# 
# engine_comparison <-
#   mutate(engine_comparison, Amount_change = Amount_Then_Year.x - Amount_Then_Year.y)
# engine_comparison <-
#   mutate(engine_comparison,
#          Amount_percent_Change = (Amount_Then_Year.x - Amount_Then_Year.y) / Amount_Then_Year.y * 100)
# colnames(engine_comparison)[colnames(engine_comparison) == "Amount_Then_Year.x"] <-
#   "Amount_Then_Year"
# 
# engine_comparison <-
#   select(engine_comparison,
#          FY,
#          ProjectName,
#          Amount_Then_Year,
#          Amount_change,
#          Amount_percent_Change)
# 
# engine_comparison$FY <- as.character(engine_comparison$FY)
# engine_comparison$FY <- as.factor(engine_comparison$FY)
# 
# engine_comparison2 <-
#   filter(engine_comparison, ProjectName == "Aerospace Fuels")
# 
# engine_comparison <- engine_comparison %>%
#   filter()
# 
# # --------------------------------------------------------------------------------
# # chart comparison 
# 
# engines_DOD_US <- engine_comparison %>%
#   filter(ProjectName == "dod_total" |
#            ProjectName == "Engines" | ProjectName == "us_total")
# 
# engines_DOD_US$FY = as.character(engines_DOD_US$FY)
# 
# engines <- engines_DOD_US %>%
#   filter(ProjectName == "Engines")
# 
# eng.baseyear <- engines$Amount_Then_Year[engines$FY == 2000]
# 
# DOD <- engines_DOD_US %>%
#   filter(ProjectName == "dod_total")
# 
# dod.baseyear <- DOD$Amount_Then_Year[DOD$FY == 2000]
# 
# US <- engines_DOD_US %>%
#   filter(ProjectName == "us_total")
# 
# US.baseyear <- US$Amount_Then_Year[US$FY == 2000]
# 
# base_year.eng <- engines %>%
#   filter(FY >= 2000) %>%
#   mutate(Amount_change = Amount_Then_Year - eng.baseyear) %>%
#   mutate(Amount_percent_change = (Amount_change) / eng.baseyear * 100) %>%
#   mutate(base = 100) %>%
#   mutate(Amount_Then_Year = base + Amount_percent_change)
# 
# base_year.DOD <- DOD %>%
#   filter(FY >= 2000) %>%
#   mutate(Amount_change = Amount_Then_Year - dod.baseyear) %>%
#   mutate(Amount_percent_change = (Amount_change) / dod.baseyear * 100) %>%
#   mutate(base = 100) %>%
#   mutate(Amount_Then_Year = base + Amount_percent_change)
# 
# base_year.US <- US %>%
#   filter(FY >= 2000) %>%
#   mutate(Amount_change = Amount_Then_Year - US.baseyear) %>%
#   mutate(Amount_percent_change = (Amount_change) / US.baseyear * 100) %>%
#   mutate(base = 100) %>%
#   mutate(Amount_Then_Year = base + Amount_percent_change)
# 
# eng.all <- rbind(base_year.eng, base_year.DOD, base_year.US)
# 
# eng.all$ProjectName[eng.all$ProjectName == "dod_total"] = "Total DOD"
# eng.all$ProjectName[eng.all$ProjectName == "us_total"] = "Total US"
# 
# eng.all <- eng.all %>%
#   group_by(FY, ProjectName) %>%
#   dplyr::summarise(Amount_Then_Year = sum(Amount_Then_Year, na.rm = TRUE))
# 
# eng.all$FY <- as.factor(eng.all$FY)
# 
# (
#   eng_US_DOD.comp <- eng.all %>%
#     ggplot() +
#     geom_line(aes(
#       x = FY, y = Amount_Then_Year, group = 1
#     ), size = 1) +
#     geom_hline(yintercept = 100, color = "#554449") +
#     facet_wrap(~ ProjectName) +
#     chart_theme +
#     scale_y_continuous(label = unit_format(unit = "M", scale = 1e-6)) +
#     scale_x_discrete(
#       breaks = seq(2000, 2018, by = 2),
#       labels = function(x) {
#         paste("'",substring(as.character(x), 3, 4),sep="")
#       }
#     ) +
#     xlab("Fiscal Year")
# )
# 
# # ggsave(
# #   "charts/engine_DoD_US_comparison.svg",
# #   eng_US_DOD.comp,
# #   device = "svg",
# #   width = 10,
# #   height = 6,
# #   units = "in"
# # )
# 

```

